### ISSUE TITLE
I am getting error in my termux

### ISSUE THREAD

**Issue by lokeshpscmr007** [haroonawanofficial/XSS-Finder#5]
![Screenshot_2019-11-10-14-17-12-330_com termux](https://user-images.githubusercontent.com/31162060/68542282-185cbb00-03d1-11ea-8f1e-9afcd1652904.jpg)

**Comment by haroonawanofficial** [comment]
Your python have missing modules in termux, simple type: pip install html , it will fix it

**Comment by 0zanAgd** [comment]
I am getting error in my linux

![err](https://user-images.githubusercontent.com/53262471/68995732-f4521b80-08a1-11ea-907e-005da4bdddd2.jpg)

**Comment by lokeshpscmr007** [comment]
![Screenshot_2019-11-16-21-30-01-709_com termux](https://user-images.githubusercontent.com/31162060/68995844-469e3700-08b8-11ea-9c9a-90a8c1932b53.jpg)

**Comment by haroonawanofficial** [comment]
First enter: pip install html --verbose, post here. Second show me logs
