### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by cybertron10** [haroonawanofficial/XSS-Finder#6]
False Positive results Also for Dom xss it just tries few payloads.

![DOM](https://user-images.githubusercontent.com/56225601/69452146-07278d00-0d87-11ea-9359-fff5be500cf2.png)

![False Poisitive](https://user-images.githubusercontent.com/56225601/69451734-1954fb80-0d86-11ea-98b6-21420ed3cec0.png)

**Comment by haroonawanofficial** [comment]
1. False positive occurs, when payload file have hidden spaces or hidden cr, nl characters in it
2. Dom feature is experimental, dom project is dropped in it as new node js will take over dom xss scanner soon
3. Add more dom payloads in dom file or other payloads to their representative payload files to see results
4. You can get more payloads from github or other sources

**Comment by cybertron10** [comment]
Anyways its a good tool. I was searching from long time.

**Comment by cybertron10** [comment]
can you add option to input file containing urls?

**Comment by haroonawanofficial** [comment]
Sure I can do that

**Comment by haroonawanofficial** [comment]
Working on new version, I will upload soon

**Comment by haroonawanofficial** [comment]
Your format was wrong, it will not find it automatically, please do something like this:

../help/en/fax_manager.htm?dom_variable_here# <- dom here (use KrA to find it)

But it is experimental. May or may not simply work.

**Comment by haroonawanofficial** [comment]
Interface.sh is updated with LIVE DOM SINK SCANNER and Automatic DOM payload test using firefox with 10,000 payloads. Enjoy!
